apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbookdeployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: addressbook
    spec:
      containers:
      - name: addressbook-container
        image: bipin89/addressbook:27
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
