piVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addressbookdeployment
spec: 
  replicas: 2
  template: 
    metadata:
      labels: 
        app: addressbook
    spec: 
      containers: 
      - name: addressbook_conatiner
        image: bipin89/addressbook:latest
        ports:
        - containerPort: 8080
